package ca.uwaterloo.ece.feedet;

import org.junit.Test;

import ca.uwaterloo.ece.feedet.BuggyChangeDetectorAndValidator;

import java.io.File;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'j22nam' at '27/05/16 5:45 PM' with Gradle 2.13
 *
 * @author j22nam, @date 27/05/16 5:45 PM
 */
public class TestJITFeeDetForSingleProject {
	@Test public void testSomeLibraryMethod() {

		String project = "ignite";
		String patternName = "WrongLogicForNullChecker";
		String verbose = "-v"; // or ""
		String rootPath = System.getProperty("user.home") + "/Documents/githubProjects/apache";//"/j22nam/projects/apache"};//,"/local/j22nam/projects/google"};//System.getProperty("user.home") + "/Documents/githubProjects/apache"};

		BuggyChangeDetectorAndValidator runner = new BuggyChangeDetectorAndValidator();

		System.out.println("=================\n" + project + "\n=================");
		String [] args ={"-g",rootPath + File.separator + project,"-p", project,"-n",patternName, verbose};//, "-s", "2010-12-10 00:00:00", "-e", "2011-07-10 00:00:00"};

		runner.run(args);
	}
}
