package ca.uwaterloo.ece.feedet;
import org.junit.Test;

import ca.uwaterloo.ece.feedet.DetectionRecord;

import java.util.ArrayList;
import java.util.HashSet;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'j22nam' at '27/05/16 5:45 PM' with Gradle 2.13
 *
 * @author j22nam, @date 27/05/16 5:45 PM
 */
public class TestFeeDetAPI {
	
	HashSet<DetectionRecord> identifiedPotentialBug = new HashSet<DetectionRecord>();
	
    @Test
    public void testDetect() {
    	
    	ArrayList<DetectionRecord> detRecords = FeeDetAPI.detect(System.getProperty("user.home") + "/Documents/githubProjects/apache/lucene-solr/lucene/core/src/java/org/apache/lucene/search");
    	
    	for(DetectionRecord detRecord:detRecords){
    		System.out.println(detRecord.getPatternName() + "\n" + detRecord.getPath() + "\n" + detRecord.getLineNum() + "\n" + detRecord.getCode());
    		System.out.println(detRecord.getSurroundCode());
    	}
    }
    
    @Test
    public void testDetectBugsInAFileForASpecifiedBugPattern(){
    	
    	/* WrongEqualsOnDiffTypes
    	/Users/JC/Documents/githubProjects/apache/lucene-solr/lucene/core/src/java/org/apache/lucene/search/spans/SpanNearQuery.java
    	135
    	!clause.getField().equals(field)*/
    	ArrayList<DetectionRecord> detRecords
    	  = FeeDetAPI.detectBugsInAFileForASpecifiedBugPattern(System.getProperty("user.home") + "/Documents/githubProjects/apache/lucene-solr/lucene/core/src/java/org/apache/lucene/search/spans/SpanNearQuery.java",
    			"ca.uwaterloo.ece.feedet.bugpatterns.WrongEqualsOnDiffTypes");
    	for(DetectionRecord detRecord:detRecords){
    		System.out.println(detRecord.getPatternName() + "\n" + detRecord.getPath() + "\n" + detRecord.getLineNum() + "\n" + detRecord.getCode());
    		System.out.println(detRecord.getSurroundCode());
    	}
    }
}
