package ca.uwaterloo.ece.feedet;
import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.lib.Repository;
import org.junit.Test;

import ca.uwaterloo.ece.feedet.DetectionRecord;
import ca.uwaterloo.ece.feedet.bugpatterns.WrongClassLogName;
import ca.uwaterloo.ece.feedet.utils.JavaASTParser;
import ca.uwaterloo.ece.feedet.utils.Utils;

import static org.junit.Assert.*;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'j22nam' at '27/05/16 5:45 PM' with Gradle 2.13
 *
 * @author j22nam, @date 27/05/16 5:45 PM
 */
public class TestBugPatternWrongClassLogName {
	
	HashSet<DetectionRecord> identifiedPotentialBug = new HashSet<DetectionRecord>();
	
    @Test public void testSomeLibraryMethod() {
    	
    	String projectPathRoot1 = System.getProperty("user.home") + "/Documents/githubProjects/apache"; //System.getProperty("user.home") + "/X"; // "/Volumes/Faith/githubProjects/apache"; //System.getProperty("user.home") + "/Documents/githubProjects/apache";

    	int numOfTPs = 0;
    	
    	// TP hbase-server/src/main/java/org/apache/hadoop/hbase/util/hbck/OfflineMetaRepair.java	2706742224ec0e89dee98a7b99e91d4c2853a63c
    	// -  private static final Log LOG = LogFactory.getLog(HBaseFsck.class.getName());
    	// +  private static final Log LOG = LogFactory.getLog(OfflineMetaRepair.class.getName());
    	String projectName = "hbase";
    	String gitURI = projectPathRoot1 + File.separator + projectName;
    	String path = "hbase-server/src/main/java/org/apache/hadoop/hbase/util/hbck/OfflineMetaRepair.java";
    	String shaId = "2706742224ec0e89dee98a7b99e91d4c2853a63c~1";
 
    	detect(projectName,gitURI, path, shaId,identifiedPotentialBug);
    	assertEquals(++numOfTPs,identifiedPotentialBug.size());
    	
    	// FP hive	Alive	bbf0629a5a2e43531c4fd5e17d727497e89d267d
    	// metastore/src/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java	126	
    	// LoggerFactory.getLogger(CachedStore.class.getName())
    	projectName = "hive";
    	gitURI = projectPathRoot1 + File.separator + projectName;
    	path = "metastore/src/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java";
    	shaId = "bbf0629a5a2e43531c4fd5e17d727497e89d267d";
 
    	detect(projectName,gitURI, path, shaId,identifiedPotentialBug);
    	assertEquals(numOfTPs,identifiedPotentialBug.size());
    	
    	// FP accumulo	e4583eb3da30b31588bbdb6698110f5d53c472e1	6bc67602c66f2cb88de5f7d8863701ac76309ab0
    	// server/base/src/main/java/org/apache/accumulo/server/rpc/TNonblockingServerSocket.java
    	// extends
    	projectName = "accumulo";
    	gitURI = projectPathRoot1 + File.separator + projectName;
    	path = "server/base/src/main/java/org/apache/accumulo/server/rpc/TNonblockingServerSocket.java";
    	shaId = "6bc67602c66f2cb88de5f7d8863701ac76309ab0";
 
    	detect(projectName,gitURI, path, shaId,identifiedPotentialBug);
    	assertEquals(numOfTPs,identifiedPotentialBug.size());
    }

	private void detect(String prjName, String gitURI, String path, String shaId,HashSet<DetectionRecord> identifiedPotentialBug) {
		try {
    		Git git;
			git = Git.open( new File(gitURI) );
			Repository repo = git.getRepository();
			
			String fileSource=Utils.fetchBlob(repo, shaId, path);
			
			fileSource = Utils.removeComments(fileSource);
			
			JavaASTParser preFixWholeCodeAST = new JavaASTParser(fileSource);
			
			process(prjName,new WrongClassLogName(prjName,preFixWholeCodeAST,shaId,path,repo).detect());
			
		} catch (IOException e1) {
			e1.printStackTrace();
		}
	}

	private void process(String projectName,ArrayList<DetectionRecord> detectionRecords) {
		for(DetectionRecord detRec:detectionRecords){
			if(!identifiedPotentialBug.contains(detRec)){
				identifiedPotentialBug.add(detRec);
				System.out.println(detRec.getPatternName() + "\t" 
						+ projectName + "\t"
						+ detRec.getRevID() + "\t"
						+ detRec.getLineNum() + "\t"
						+ detRec.getPath());
				System.out.println(detRec.getCode() + "\n");
			}
		}
		
	}
}
